import json

path = r"C:\Users\guopi\GitHub\courses\future-media-internet\labs\kaggle-demos\demo2-qoe-optimization.ipynb"
with open(path, "r", encoding="utf-8") as f:
    nb = json.load(f)

# Fix cell 3 - the simulator
nb["cells"][3]["source"] = [
    "# Video playback simulator\n",
    "QUALITY_LEVELS = [2, 5, 10]  # Mbps: Low, Medium, High\n",
    "CHUNK_DURATION = 2.0  # seconds per chunk\n",
    "STEP_DURATION = 0.5  # seconds per simulation step\n",
    "\n",
    "def simulate(bandwidth, strategy_fn, label):\n",
    "    buffer = 5.0  # initial buffer (seconds)\n",
    "    quality = 1  # start at medium\n",
    "    \n",
    "    history = {'buffer': [], 'quality': [], 'stall': []}\n",
    "    total_stall = 0\n",
    "    quality_changes = 0\n",
    "    prev_quality = quality\n",
    "    \n",
    "    for bw in bandwidth:\n",
    "        # Download: in STEP_DURATION seconds, we get bw*STEP_DURATION Mb of data\n",
    "        # That data equals (bw*STEP_DURATION / bitrate) seconds of video\n",
    "        data_downloaded = bw * STEP_DURATION  # Mb\n",
    "        video_seconds = data_downloaded / QUALITY_LEVELS[quality]  # seconds of video\n",
    "        buffer += video_seconds  # add to buffer\n",
    "        buffer -= STEP_DURATION  # consume playback time\n",
    "        \n",
    "        # Stall detection\n",
    "        stalled = buffer <= 0\n",
    "        if stalled:\n",
    "            total_stall += 1\n",
    "            buffer = 0.0\n",
    "        \n",
    "        # Make decision for next chunk\n",
    "        quality = strategy_fn(buffer, quality, bw, history)\n",
    "        quality = max(0, min(2, quality))\n",
    "        \n",
    "        if quality != prev_quality:\n",
    "            quality_changes += 1\n",
    "            prev_quality = quality\n",
    "        \n",
    "        history['buffer'].append(buffer)\n",
    "        history['quality'].append(QUALITY_LEVELS[quality])\n",
    "        history['stall'].append(stalled)\n",
    "    \n",
    "    # QoE score\n",
    "    avg_quality = np.mean(history['quality'])\n",
    "    stall_penalty = total_stall * 3\n",
    "    switch_penalty = quality_changes * 0.5\n",
    "    qoe = avg_quality - stall_penalty - switch_penalty\n",
    "    \n",
    "    return history, dict(label=label, avg_quality=avg_quality,\n",
    "                         stalls=total_stall, switches=quality_changes, qoe=qoe)\n",
    "\n",
    'print("Simulator ready")\n',
]

# Also fix cell 4 - strategies, remove Chinese comments
nb["cells"][4]["source"] = [
    "# Strategy 1: Always highest bitrate\n",
    "def strategy_fixed(buffer, quality, bw, history):\n",
    "    return 2\n",
    "\n",
    "# Strategy 2: Buffer-driven heuristic\n",
    "def strategy_heuristic(buffer, quality, bw, history):\n",
    "    if buffer < 3:\n",
    "        return 0  # low buffer -> drop to low\n",
    "    elif buffer > 10:\n",
    "        return 2  # plenty of buffer -> go high\n",
    "    elif buffer > 5:\n",
    "        return 1  # moderate -> medium\n",
    "    return quality\n",
    "\n",
    "# Strategy 3: Pre-trained Q-table\n",
    "Q_table = np.array([0, 0, 1, 2, 2])  # 5 buffer states -> optimal actions\n",
    "def strategy_qlearning(buffer, quality, bw, history):\n",
    "    state = min(int(buffer // 5), 4)\n",
    "    if np.random.random() < 0.1:  # 10% exploration\n",
    "        return np.random.randint(0, 3)\n",
    "    return Q_table[state]\n",
    "\n",
    'print("3 strategies defined")\n',
    'print(f"Q-table: {Q_table}")\n',
    'print("Buffer 0-5s -> Low | 5-10s -> Low | 10-15s -> Med | 15-20s -> High | 20s+ -> High")\n',
]

# Fix cell 5 - run strategies
nb["cells"][5]["source"] = [
    "# Run all three strategies\n",
    "hist_fixed, stats_fixed = simulate(bandwidth, strategy_fixed, 'Fixed')\n",
    "hist_heur, stats_heur = simulate(bandwidth, strategy_heuristic, 'Heuristic')\n",
    "hist_ql, stats_ql = simulate(bandwidth, strategy_qlearning, 'Q-Learning')\n",
    "\n",
    'print("\\n========== Results ==========")\n',
    'for s in [stats_fixed, stats_heur, stats_ql]:\n',
    '    print(f"{s[\"label\"]:12s} | AvgQ:{s[\"avg_quality\"]:5.1f} | Stalls:{s[\"stalls\"]:3d} | Switches:{s[\"switches\"]:3d} | QoE:{s[\"qoe\"]:6.1f}")\n',
]

# Fix cell 6 - visualization, fix the title format
nb["cells"][6]["source"] = [
    "# Visualization\n",
    "fig, axes = plt.subplots(3, 1, figsize=(14, 10), sharex=True)\n",
    "\n",
    "histories = [hist_fixed, hist_heur, hist_ql]\n",
    "strategy_names = ['Fixed High Bitrate', 'Heuristic Buffer-Based', 'Q-Learning Adaptive']\n",
    "colors = ['#e74c3c', '#f39c12', '#2ecc71']\n",
    "time_axis = t * STEP_DURATION\n",
    "\n",
    "for i, (hist, name, color) in enumerate(zip(histories, strategy_names, colors)):\n",
    "    ax1 = axes[i]\n",
    "    ax2 = ax1.twinx()\n",
    "    \n",
    "    # Bitrate selection\n",
    "    ax1.step(time_axis, hist['quality'], where='post', color=color, linewidth=2)\n",
    "    ax1.set_ylabel('Bitrate (Mbps)', color=color)\n",
    "    ax1.set_ylim(0, 12)\n",
    "    ax1.tick_params(axis='y', labelcolor=color)\n",
    "    \n",
    "    # Mark stalls\n",
    "    stall_times = time_axis[np.array(hist['stall']).astype(bool)]\n",
    "    for st in stall_times:\n",
    "        ax1.axvline(x=st, color='red', alpha=0.3, linewidth=3)\n",
    "    \n",
    "    # Buffer level\n",
    "    ax2.plot(time_axis, hist['buffer'], 'gray', alpha=0.4, linewidth=1)\n",
    "    ax2.set_ylabel('Buffer (s)', color='gray')\n",
    "    ax2.set_ylim(0, 20)\n",
    "    \n",
    "    ax1.set_title(f'{name} | Stalls: {np.sum(hist[\"stall\"]):.0f}', fontsize=13)\n",
    "    ax1.grid(True, alpha=0.2)\n",
    "\n",
    "axes[-1].set_xlabel('Time (s)')\n",
    "plt.tight_layout()\n",
    "plt.show()\n",
    "\n",
    'print("\\nDiscussion:")\n',
    'print("1. Fixed strategy stalls when bandwidth drops below bitrate")\n',
    'print("2. Heuristic avoids stalls but switches quality too often")\n',
    'print("3. Q-Learning stays stable - it learned the bandwidth pattern")\n',
    'print("4. Real systems (YouTube) use heuristics because RL needs retraining per user")\n',
]

with open(path, "w", encoding="utf-8") as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)
print("demo2 simulator and all texts fixed")
